name: Generate Bindings for Spine Protos

on:
  push:
    branches:
      - main

jobs:
  generate_go_bindings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout spine-protos
        uses: actions/checkout@v4
        with:
          repository: the-spine/spine-protos
          ref: main
          token: ${{ secrets.PROTO_GEN_TOKEN }}
          path: spine-protos

      - name: Checkout spine-protos-go
        uses: actions/checkout@v4
        with:
          repository: the-spine/spine-protos-go
          ref: main
          token: ${{ secrets.PROTO_GEN_TOKEN }}
          path: spine-protos-go

      - name: Checkout spine-protos-dart
        uses: actions/checkout@v4
        with:
          repository: the-spine/spine-protos-dart
          ref: main
          token: ${{ secrets.PROTO_GEN_TOKEN }}
          path: spine-protos-dart

          

      - name: Check Current Directory
        run: |
          pwd
          ls 
          ls ../
          ls ~


      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.3"

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
          channel: stable
      
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get -y install protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          dart pub global activate protoc_plugin

      - name: Generate Bindings
        run: |
          cd spine-protos
          export GENERATED_DIR_GO=../spine-protos-go
          export GENERATED_DIR_DART=../spine-protos-dart
          make

      - name: Push Go Bindings
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          commit_message="${{ github.event.head_commit.message }}"
          cd spine-protos-go
          git add . && git diff-index --quiet HEAD || git commit -m "$commit_message" && git push        


      - name: Push Dart Bindings
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          commit_message="${{ github.event.head_commit.message }}"
          cd spine-protos-dart
          git add . && git diff-index --quiet HEAD || git commit -m "$commit_message" && git push        
